### ISSUE TITLE
Change the contents of LICENSE.

### ISSUE THREAD

**Issue by ExeTwezz** [ExeTwezz/Basic_OS#1]

**Comment by rzhikharevich** [comment]
А что не так с лицензией?

**Comment by ExeTwezz** [comment]
Да мне вот эти слова показались странными:
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
Посмотрел в http://choosealicense.com/licenses/mit/ — оказывается, всё правильно.
